### ISSUE TITLE
Support Request: Prevent dropdown from closing when scrolling inside the dropdown on mobile

### ISSUE THREAD

**Issue by rangelke** [oferh/ng2-completer#206]
Due to a massive array, it's really massive. Although we want to show all possible items after typing in 3 characters, which results in a massive dropdown and is not so nice to look at. 

Using shadow piercing selecter I was able to change styling of the dropdown. 
```css
/deep/ .completer-dropdown {
    width: 32% !important;
    overflow-y: auto;
    overflow-x: hidden;
    height: 10rem;
}
```

The dropdown now shows a couple items and on a computer it's perfectly possible to scroll down in the dropdown. However on mobile, whenever you want to scroll down, it selects an item and closes the dropdown. Probably caused by the fact that `(selected: CompleterItem): void` emits an event when touching the screen trying to scroll down.

**Comment by rangelke** [comment]
@oferh 
There is no way at the moment to prevent this behavior in the current state of the library?
If so, I can try look into possible solutions, but help is welcome of course.

**Comment by oferh** [comment]
@rangelke the demo works on my mobile but haven't tested it on multiple devices.
can you provide a plunk and let me know which device are you checking on?

**Comment by rangelke** [comment]
@oferh I just realized the same thing, your demo works on the tested device. I'm gonna look into it and get back when I have more info!

**Comment by rangelke** [comment]
@oferh Silly me, I was still using 1.2.1 and I see in 1.3.0 the issue should have been resolved. Upgrading to 1.3.0 should solve the problem, however I can't build the application anymore after upgrading to 1.3.0

**Comment by oferh** [comment]
Why not 1.4.0?

**Comment by rangelke** [comment]
@oferh 1.3.0 and 1.3.1. just crashes when the app gets initialied and 1.4.0 throws the following errors when compiling: 
```

ERROR in C:\Users\debaeke\Documents\projecten\freebility\fb-dewatergroep\fb-dewatergroep-moka-frontend\node_modules\ng2-completer\directives\ctr-completer.d.ts
(41,14): error TS1005: '=' expected.

ERROR in C:\Users\debaeke\Documents\projecten\freebility\fb-dewatergroep\fb-dewatergroep-moka-frontend\node_modules\ng2-completer\directives\ctr-completer.d.ts
(41,25): error TS1005: ';' expected.

ERROR in C:\Users\debaeke\Documents\projecten\freebility\fb-dewatergroep\fb-dewatergroep-moka-frontend\node_modules\ng2-completer\directives\ctr-completer.d.ts
(41,14): error TS2304: Cannot find name 'hasSelected'.

ERROR in C:\Users\debaeke\Documents\projecten\freebility\fb-dewatergroep\fb-dewatergroep-moka-frontend\node_modules\ng2-completer\directives\ctr-completer.d.ts
(41,27): error TS7008: Member 'boolean' implicitly has an 'any' type.
```

**Comment by oferh** [comment]
can you provide a repo or a plunker that reproduces the issue?

**Comment by rangelke** [comment]
@oferh 
I updated all angular related packages from 2.1 to 2.4, the router from 3.0 to 3.4
The typescript from 1.8.10 to 2.1, ts-loader from 0.4 to 2.1 and rxjs from beta to 5.1.

Not sure which package solved the problem, but at least my app is able to build + run now and the issue is fixed using ng2-completer v1.4.0. 

I don't think it's a bad thing the app undergoes those changes, the pain is that some functional testing should be done now in order to check if everything still works, but at the moment everything looks good so far. 

Issue can be closed!
